version: '3.7'
services:
  football-score-api:
    build:
      context: .
      target: development
    ports:
      - "9229:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
